
package ehealth.controller_storage.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import ehealth.controller_db.ws.Goal;
import ehealth.controller_db.ws.HealthMeasureHistory;
import ehealth.controller_db.ws.MeasureDefinition;
import ehealth.controller_db.ws.Person;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceStorage", targetNamespace = "http://ws.controller_storage.ehealth/")
@XmlSeeAlso({
    ehealth.controller_db.ws.ObjectFactory.class,
    ehealth.controller_storage.ws.ObjectFactory.class
})
public interface ServiceStorage {


    /**
     * 
     * @param idPerson
     * @return
     *     returns ehealth.controller_db.ws.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "readPerson", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.ReadPerson")
    @ResponseWrapper(localName = "readPersonResponse", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.ReadPersonResponse")
    @Action(input = "http://ws.controller_storage.ehealth/ServiceStorage/readPersonRequest", output = "http://ws.controller_storage.ehealth/ServiceStorage/readPersonResponse")
    public Person readPerson(
        @WebParam(name = "idPerson", targetNamespace = "")
        Long idPerson);

    /**
     * 
     * @return
     *     returns java.util.List<ehealth.controller_db.ws.Person>
     */
    @WebMethod
    @WebResult(name = "people", targetNamespace = "")
    @RequestWrapper(localName = "readPersonList", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.ReadPersonList")
    @ResponseWrapper(localName = "readPersonListResponse", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.ReadPersonListResponse")
    @Action(input = "http://ws.controller_storage.ehealth/ServiceStorage/readPersonListRequest", output = "http://ws.controller_storage.ehealth/ServiceStorage/readPersonListResponse")
    public List<Person> readPersonList();

    /**
     * 
     * @param person
     */
    @WebMethod
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.UpdatePersonResponse")
    @Action(input = "http://ws.controller_storage.ehealth/ServiceStorage/updatePersonRequest", output = "http://ws.controller_storage.ehealth/ServiceStorage/updatePersonResponse")
    public void updatePerson(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @param person
     * @return
     *     returns ehealth.controller_db.ws.Person
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.CreatePersonResponse")
    @Action(input = "http://ws.controller_storage.ehealth/ServiceStorage/createPersonRequest", output = "http://ws.controller_storage.ehealth/ServiceStorage/createPersonResponse")
    public Person createPerson(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @param person
     */
    @WebMethod
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.DeletePersonResponse")
    @Action(input = "http://ws.controller_storage.ehealth/ServiceStorage/deletePersonRequest", output = "http://ws.controller_storage.ehealth/ServiceStorage/deletePersonResponse")
    public void deletePerson(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @param idPerson
     * @param measureType
     * @return
     *     returns java.util.List<ehealth.controller_db.ws.HealthMeasureHistory>
     */
    @WebMethod
    @WebResult(name = "measure", targetNamespace = "")
    @RequestWrapper(localName = "readPersonHistory", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.ReadPersonHistory")
    @ResponseWrapper(localName = "readPersonHistoryResponse", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.ReadPersonHistoryResponse")
    @Action(input = "http://ws.controller_storage.ehealth/ServiceStorage/readPersonHistoryRequest", output = "http://ws.controller_storage.ehealth/ServiceStorage/readPersonHistoryResponse")
    public List<HealthMeasureHistory> readPersonHistory(
        @WebParam(name = "idPerson", targetNamespace = "")
        Long idPerson,
        @WebParam(name = "measureType", targetNamespace = "")
        String measureType);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(name = "measureTypes", targetNamespace = "")
    @RequestWrapper(localName = "readMeasureTypes", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.ReadMeasureTypes")
    @ResponseWrapper(localName = "readMeasureTypesResponse", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.ReadMeasureTypesResponse")
    @Action(input = "http://ws.controller_storage.ehealth/ServiceStorage/readMeasureTypesRequest", output = "http://ws.controller_storage.ehealth/ServiceStorage/readMeasureTypesResponse")
    public List<String> readMeasureTypes();

    /**
     * 
     * @param idPerson
     * @param mid
     * @param measureType
     * @return
     *     returns ehealth.controller_db.ws.HealthMeasureHistory
     */
    @WebMethod
    @WebResult(name = "measure", targetNamespace = "")
    @RequestWrapper(localName = "readPersonMeasure", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.ReadPersonMeasure")
    @ResponseWrapper(localName = "readPersonMeasureResponse", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.ReadPersonMeasureResponse")
    @Action(input = "http://ws.controller_storage.ehealth/ServiceStorage/readPersonMeasureRequest", output = "http://ws.controller_storage.ehealth/ServiceStorage/readPersonMeasureResponse")
    public HealthMeasureHistory readPersonMeasure(
        @WebParam(name = "idPerson", targetNamespace = "")
        Long idPerson,
        @WebParam(name = "measureType", targetNamespace = "")
        String measureType,
        @WebParam(name = "mid", targetNamespace = "")
        Long mid);

    /**
     * 
     * @param idPerson
     * @param measure
     * @return
     *     returns ehealth.controller_db.ws.HealthMeasureHistory
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "savePersonMeasure", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.SavePersonMeasure")
    @ResponseWrapper(localName = "savePersonMeasureResponse", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.SavePersonMeasureResponse")
    @Action(input = "http://ws.controller_storage.ehealth/ServiceStorage/savePersonMeasureRequest", output = "http://ws.controller_storage.ehealth/ServiceStorage/savePersonMeasureResponse")
    public HealthMeasureHistory savePersonMeasure(
        @WebParam(name = "idPerson", targetNamespace = "")
        Long idPerson,
        @WebParam(name = "measure", targetNamespace = "")
        HealthMeasureHistory measure);

    /**
     * 
     * @param idPerson
     * @param measure
     * @return
     *     returns ehealth.controller_db.ws.HealthMeasureHistory
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePersonMeasure", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.UpdatePersonMeasure")
    @ResponseWrapper(localName = "updatePersonMeasureResponse", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.UpdatePersonMeasureResponse")
    @Action(input = "http://ws.controller_storage.ehealth/ServiceStorage/updatePersonMeasureRequest", output = "http://ws.controller_storage.ehealth/ServiceStorage/updatePersonMeasureResponse")
    public HealthMeasureHistory updatePersonMeasure(
        @WebParam(name = "idPerson", targetNamespace = "")
        Long idPerson,
        @WebParam(name = "measure", targetNamespace = "")
        HealthMeasureHistory measure);

    /**
     * 
     * @param measureType
     * @return
     *     returns ehealth.controller_db.ws.MeasureDefinition
     */
    @WebMethod
    @WebResult(name = "measureType", targetNamespace = "")
    @RequestWrapper(localName = "readMeasureType", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.ReadMeasureType")
    @ResponseWrapper(localName = "readMeasureTypeResponse", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.ReadMeasureTypeResponse")
    @Action(input = "http://ws.controller_storage.ehealth/ServiceStorage/readMeasureTypeRequest", output = "http://ws.controller_storage.ehealth/ServiceStorage/readMeasureTypeResponse")
    public MeasureDefinition readMeasureType(
        @WebParam(name = "measureType", targetNamespace = "")
        String measureType);

    /**
     * 
     * @param goal
     * @return
     *     returns ehealth.controller_db.ws.Goal
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateGoal", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.UpdateGoal")
    @ResponseWrapper(localName = "updateGoalResponse", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.UpdateGoalResponse")
    @Action(input = "http://ws.controller_storage.ehealth/ServiceStorage/updateGoalRequest", output = "http://ws.controller_storage.ehealth/ServiceStorage/updateGoalResponse")
    public Goal updateGoal(
        @WebParam(name = "goal", targetNamespace = "")
        Goal goal);

    /**
     * 
     * @param idPerson
     * @return
     *     returns java.util.List<ehealth.controller_db.ws.Goal>
     */
    @WebMethod
    @WebResult(name = "goals", targetNamespace = "")
    @RequestWrapper(localName = "readGoalList", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.ReadGoalList")
    @ResponseWrapper(localName = "readGoalListResponse", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.ReadGoalListResponse")
    @Action(input = "http://ws.controller_storage.ehealth/ServiceStorage/readGoalListRequest", output = "http://ws.controller_storage.ehealth/ServiceStorage/readGoalListResponse")
    public List<Goal> readGoalList(
        @WebParam(name = "idPerson", targetNamespace = "")
        Long idPerson);

    /**
     * 
     * @param idPerson
     * @return
     *     returns java.util.List<ehealth.controller_db.ws.Goal>
     */
    @WebMethod
    @WebResult(name = "goals", targetNamespace = "")
    @RequestWrapper(localName = "readLatestGoalList", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.ReadLatestGoalList")
    @ResponseWrapper(localName = "readLatestGoalListResponse", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.ReadLatestGoalListResponse")
    @Action(input = "http://ws.controller_storage.ehealth/ServiceStorage/readLatestGoalListRequest", output = "http://ws.controller_storage.ehealth/ServiceStorage/readLatestGoalListResponse")
    public List<Goal> readLatestGoalList(
        @WebParam(name = "idPerson", targetNamespace = "")
        Long idPerson);

    /**
     * 
     * @param goal
     * @return
     *     returns ehealth.controller_db.ws.Goal
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveGoal", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.SaveGoal")
    @ResponseWrapper(localName = "saveGoalResponse", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.SaveGoalResponse")
    @Action(input = "http://ws.controller_storage.ehealth/ServiceStorage/saveGoalRequest", output = "http://ws.controller_storage.ehealth/ServiceStorage/saveGoalResponse")
    public Goal saveGoal(
        @WebParam(name = "goal", targetNamespace = "")
        Goal goal);

    /**
     * 
     * @param idPerson
     * @param before
     * @param after
     * @param measureType
     * @return
     *     returns java.util.List<ehealth.controller_db.ws.HealthMeasureHistory>
     */
    @WebMethod
    @WebResult(name = "measure", targetNamespace = "")
    @RequestWrapper(localName = "readMeasureHistoriesByDate", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.ReadMeasureHistoriesByDate")
    @ResponseWrapper(localName = "readMeasureHistoriesByDateResponse", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.ReadMeasureHistoriesByDateResponse")
    @Action(input = "http://ws.controller_storage.ehealth/ServiceStorage/readMeasureHistoriesByDateRequest", output = "http://ws.controller_storage.ehealth/ServiceStorage/readMeasureHistoriesByDateResponse")
    public List<HealthMeasureHistory> readMeasureHistoriesByDate(
        @WebParam(name = "idPerson", targetNamespace = "")
        Long idPerson,
        @WebParam(name = "measureType", targetNamespace = "")
        String measureType,
        @WebParam(name = "before", targetNamespace = "")
        XMLGregorianCalendar before,
        @WebParam(name = "after", targetNamespace = "")
        XMLGregorianCalendar after);

    /**
     * 
     * @param weight
     * @param height
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "bmi", targetNamespace = "")
    @RequestWrapper(localName = "readBmi", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.ReadBmi")
    @ResponseWrapper(localName = "readBmiResponse", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.ReadBmiResponse")
    @Action(input = "http://ws.controller_storage.ehealth/ServiceStorage/readBmiRequest", output = "http://ws.controller_storage.ehealth/ServiceStorage/readBmiResponse")
    public String readBmi(
        @WebParam(name = "weight", targetNamespace = "")
        double weight,
        @WebParam(name = "height", targetNamespace = "")
        double height);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "quote", targetNamespace = "")
    @RequestWrapper(localName = "readQuote", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.ReadQuote")
    @ResponseWrapper(localName = "readQuoteResponse", targetNamespace = "http://ws.controller_storage.ehealth/", className = "ehealth.controller_storage.ws.ReadQuoteResponse")
    @Action(input = "http://ws.controller_storage.ehealth/ServiceStorage/readQuoteRequest", output = "http://ws.controller_storage.ehealth/ServiceStorage/readQuoteResponse")
    public String readQuote();

}
